spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-boke?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8


#Mybatis输出sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置
zf:
  #  本地文件上传路径
  local-upload-path: /Users/dingchangqing/Downloads/zfxf/oa/
  #  上传方式：local-本地上传  alioss-阿里云Oss
  upload-type: local
