spring:
  datasource:
    url: jdbc:mysql://192.168.5.250:3306/zf_sq?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
    username: dev2019
    password: Zf2019@)!(
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  #redis 配置
  redis:
    database: 0
    host: 192.168.5.250
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: '1234'
    port: 6389
  rabbitmq:
    host: 192.168.5.250
    port: 5672
    username: isafe
    password: Isafe@)!*
# 自定义配置
zf:
  #  本地文件上传路径
  local-upload-path: /home/songtao/java/zf_oa/files/
  #  上传方式：local-本地上传  alioss-阿里云Oss
  upload-type: local